# Generated by Django 4.2.7 on 2026-03-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_alter_analysisjob_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIQuotaTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_index', models.IntegerField(help_text='Index in GEMINI_API_KEYS list')),
                ('date', models.DateField(help_text='Tracking date')),
                ('tokens_used', models.IntegerField(default=0)),
                ('requests_made', models.IntegerField(default=0)),
                ('is_exhausted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'API Quota Tracker',
                'verbose_name_plural': 'API Quota Trackers',
                'unique_together': {('key_index', 'date')},
            },
        ),
    ]
