# Generated by Django 4.2.7 on 2026-03-01 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_add_ai_analysis_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='needs_review',
            field=models.BooleanField(default=False, help_text='True if question text is suspiciously short or was flagged during validation'),
        ),
        migrations.AddField(
            model_name='question',
            name='sub_part',
            field=models.CharField(blank=True, help_text='Empty for Part A, a or b for Part B sub-questions', max_length=5),
        ),
        migrations.AlterField(
            model_name='question',
            name='frequency_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='question',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='question',
            name='importance_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(blank=True, choices=[('definition', 'Definition'), ('derivation', 'Derivation'), ('numerical', 'Numerical Problem'), ('theory', 'Theoretical'), ('diagram', 'Diagram-based'), ('comparison', 'Comparison'), ('short_answer', 'Short Answer'), ('long_answer', 'Long Answer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='repetition_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='years_appeared',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
