# Generated by Django 4.2.7 on 2026-03-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_question_needs_review_question_sub_part_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(check=models.Q(('marks__gt', 0), ('marks__isnull', True), _connector='OR'), name='question_marks_positive'),
        ),
    ]
