# Generated by Django 4.2.7 on 2026-03-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_question_question_marks_positive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='part',
            field=models.CharField(blank=True, db_index=True, help_text='Part A or Part B', max_length=1),
        ),
    ]
