# Generated by Django 4.2.7 on 2026-03-01 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_paper_progress_percent_paper_questions_classified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='correction_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of module corrections applied by the validator'),
        ),
        migrations.AddField(
            model_name='paper',
            name='detected_exam_month',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='paper',
            name='detected_exam_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='detected_subject_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='paper',
            name='detected_subject_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paper',
            name='processing_log',
            field=models.TextField(blank=True, help_text='Detailed processing log as JSON string'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='progress_percent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paper',
            name='questions_classified',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paper',
            name='questions_extracted',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paper',
            name='status_detail',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
