# Generated by Django 4.2.7 on 2026-03-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_paper_correction_count_paper_detected_exam_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='extraction_quality_score',
            field=models.PositiveIntegerField(default=0, help_text='Quality score from extraction (0-110). Below 60 means needs review.'),
        ),
    ]
