# Generated by Django 4.2.7 on 2026-03-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0005_paper_extraction_quality_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when processing started (for speed tracking)', null=True),
        ),
    ]
