# Generated by Django 4.2.7 on 2026-03-01 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_topiccluster_cluster_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topiccluster',
            name='cluster_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='topiccluster',
            name='frequency_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='topiccluster',
            name='priority_tier',
            field=models.IntegerField(choices=[(1, 'Top Priority (5+ exams)'), (2, 'High Priority (3-4 exams)'), (3, 'Medium Priority (2 exams)'), (4, 'Low Priority (1 exam)')], default=4),
        ),
        migrations.AlterField(
            model_name='topiccluster',
            name='question_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='topiccluster',
            name='total_marks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='topiccluster',
            name='years_appeared',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
